### ISSUE TITLE
Save the last message for use in the background

### ISSUE THREAD

**Issue by BugsOverBugs** [deokgyuhan/flutter_nfc_hce#1]
Hi. I really like your plugin.

I noticed that there is still a nfc signal after the app is fully closed, which I think is a great feature. The only problem is that then it always uses the default message in `KHostApduService.kt`:
`106   private var NDEF_URI = NdefMessage(createTextRecord("en", "Ciao, come va?", NDEF_ID))`

Is there any way to save the last message and use it as the new default message, even if the app is closed?

Some other helpful features would be:
- A `stopNfcHce()` method
- A paramter in `startNfcHce` to use a custom mime type, e.g. "text/vcard"

Regards, Tom

**Comment by deokgyuhan** [comment]
Hi BugsOverBugs.
Thank you for your interest in the plugin. Upon reviewing your suggestions and re-examining the code, it seems that we might need to use a different approach to retain NFC messages even after the app has exited. When I initially developed this plugin and tested it while the app was still running, I encountered issues where the NFC reader failed to accurately read NFC messages, even when the reader was slightly distant or after NFC HCE had been active for some time, resulting in the reader returning default messages.

Based on the feedback you provided in the issue and your recent suggestions, I have reconsidered the source code and potential solutions. It appears that the issue may be related to the return value of onStartCommand, specifically using START_STICKY. To retain messages even after the app has exited and ensure that the service restarts, it might be worth trying to return START_REDELIVER_INTENT.

I would appreciate your comments on my suggestion. Should you agree, I can proceed with an update using this approach. Thank you once again for your feedback, and I look forward to hearing your thoughts on my suggestion.

**Comment by BugsOverBugs** [comment]
Hello, thank you for your quick reply!

I have tested different Android devices to exchange data between them. The process was always fluent whether the app was in foreground, background or closed.
Unfortunately my knowledge of native Android code and nfc api is not that deep.
I would be happy if you can find a solution to keep the last nfc message, as the default is used when the app leaves foreground mode, which affects convenience.

**Comment by deokgyuhan** [comment]
Hi BugsOverBugs.

I have made updates to ensure that the tag message specified when starting NFC HCE for the first time is maintained in both foreground and background. 

Additionally, I have implemented the feature to read NFC HCE tags even when the app's screen is fully locked on Android 12 and higher. Furthermore, I have added the 'isSupportSecureNfcSupported' API. 

The updated version is now available on pub.dev. I would appreciate it if you could test the updated library in your project and provide feedback.

Once again, thank you for your interest in flutter_nfc_hce.

**Comment by atanasyordanov21** [comment]
@deokgyuhan Thank you for the great plugin! I'll also be glad having a method `stopNfcHce()`, because in my particular case I need to be able to turn off the service when the app is not active anymore, i.e. when closed or in background. Cheers!

**Comment by deokgyuhan** [comment]
> @deokgyuhan Thank you for the great plugin! I'll also be glad having a method `stopNfcHce()`, because in my particular case I need to be able to turn off the service when the app is not active anymore, i.e. when closed or in background. Cheers!

Hi atanasyordanov21. 
Thank you for your interest in the plugin. Always be happy and fighting!

**Comment by BugsOverBugs** [comment]
> Hi BugsOverBugs.
> 
> I have made updates to ensure that the tag message specified when starting NFC HCE for the first time is maintained in both foreground and background.
> 
> Additionally, I have implemented the feature to read NFC HCE tags even when the app's screen is fully locked on Android 12 and higher. Furthermore, I have added the 'isSupportSecureNfcSupported' API.
> 
> The updated version is now available on pub.dev. I would appreciate it if you could test the updated library in your project and provide feedback.
> 
> Once again, thank you for your interest in flutter_nfc_hce.

Thank you for this quick update.

I can confirm that the message is retained in the background and when the app is completely closed, but unfortunately it is not restored after restarting the device. It then reverts back to the hardcoded default. Is it possible to fix this as well?

When a locked device detects the NFC tag, you need to unlock it to read the tag. A nice addition :)

What about the other (smaller?) feature requests? Are they implementable?

**Comment by deokgyuhan** [comment]
Hi BugsOverBugs !

Here is a summary of the questions you inquired about:

1. Weather messages can be preserved even when the app is restarted after being closed.

2. Whether the NFC reader's detection can forcibly unlock the app's lock screen when a NFC tag is recognized
    while the device is locked.

4. Whether it's possible to request additional small features for the NFC HCE plugin.

Is this a correct summary of the three questions?

**Comment by BugsOverBugs** [comment]
I am sorry for being too imprecise. My questions are:

1. Is it possible to keep the last message after a complete reboot of the device?
2. Is it possible to implement a `stopNfcHce()` method?
3. Is it possible to implement a `mimeType` parameter in `startNfcHce` with the default value `text/plain`?

**Comment by deokgyuhan** [comment]
> I am sorry for being too imprecise. My questions are:
> 
> 1. Is it possible to keep the last message after a complete reboot of the device?
> 2. Is it possible to implement a `stopNfcHce()` method?
> 3. Is it possible to implement a `mimeType` parameter in `startNfcHce` with the default value `text/plain`?

It's okay. I understand the questions better now. I think I'll need to look into the documentation a bit more and review it. I've only been doing app development for about six months, so I still have a lot to learn, and immediate answers might be a bit challenging. However, I'll do my best to respond as quickly as possible. Thank you.

**Comment by deokgyuhan** [comment]
Hi BugsOverBugs ! 

I have reviewed the contents I examined, and they are as follows.

1. Is it possible to keep the last message after a complete reboot of the device?
-> Upon reviewing this, it seems feasible to store messages that are kept in memory onto external device storage, allowing the app to read them after a reboot.

2. Is it possible to implement a stopNfcHce() method?
-> I apologize for the confusion. I thought I had implemented the stopNfcHce() method, but I've just learned today that it doesn't exist. It seems like this could also be achievable.

3. Is it possible to implement a mimeType parameter in startNfcHce with the default value text/plain?
-> I understood this as making it possible to omit passing a message as a parameter to startNfcHce. This also seems doable.

I believe all three of these updates can be incorporated. However, it might be a good idea to separate the API-related changes. Please provide your comments on my suggestions, and I will proceed with the update accordingly.

Regarding the recent issue you mentioned about NFC HCE tags being read by iPhone reader apps triggering Apple Pay and preventing the tag's content from being read, do you happen to know if there's a way to deactivate Apple Pay when an iPhone NFC reader app is running in the foreground?

 I am an iPhone user, but I haven't used Apple Pay, so this issue is new to me. If you have any experience or insights on this matter, I would greatly appreciate it.

I hope I have understood and addressed your inquiries correctly. I apologize for any difficulty in communication due to my limited proficiency in English. Good luck!

**Comment by BugsOverBugs** [comment]
> 1. Is it possible to keep the last message after a complete reboot of the device?
>    -> Upon reviewing this, it seems feasible to store messages that are kept in memory onto external device storage, allowing the app to read them after a reboot.

It would be really helpful if this works.

> 2. Is it possible to implement a stopNfcHce() method?
>    -> I apologize for the confusion. I thought I had implemented the stopNfcHce() method, but I've just learned today that it doesn't exist. It seems like this could also be achievable.

This would also be very helpful to be able to use the feature only temporarily.

> 3. Is it possible to implement a mimeType parameter in startNfcHce with the default value text/plain?
>    -> I understood this as making it possible to omit passing a message as a parameter to startNfcHce. This also seems doable.

I would implement the `mimeType` as another non-required `String` parameter in `startNfcHce` for better customization.
I would give it the default value `"text/plain"` since this is the default value of NFC tags. This parameter must also be stored according to 1.

> Regarding the recent issue you mentioned about NFC HCE tags being read by iPhone reader apps triggering Apple Pay and preventing the tag's content from being read, do you happen to know if there's a way to deactivate Apple Pay when an iPhone NFC reader app is running in the foreground?

Yes, I have encountered this problem as well. My iPhone SE never read the NFC HCE tag. There is not setting to disable this behavior. But iPhones can also read real NFC tags, so I think it has something to do with the `AID`. Maybe the AID could be another non-required `String` parameter for `startNfcHce`, if you still need other tag types. If so, I could figure out a working parameter more easily.

Please ask me if something is unclear to you :)

**Comment by deokgyuhan** [comment]
Hi BugsOverBugs !

When I initially developed NFC HCE (Host Card Emulation) for Android, I encountered a scenario where a dialog prompt would appear asking me to choose the app when there were multiple apps with the same AID (Application Identifier).

In a similar context, can we understand the situation where Apple Pay automatically opens when trying to read an NFC HCE tag from an iPhone reader? After reading the Apple developer site and Stack Overflow content for several days and reviewing it, I found information suggesting that you can control the automatic opening of Apple Pay from the app acting as a reader. 

However, I'm not entirely sure if providing the ability to change the AID within the flutter_nfc_hce plugin, as you suggested, would prevent Apple Pay from automatically opening in the reader. Initially, the purpose of developing this plugin was to leverage NFC for cross-platform use, specifically to support HCE on Android, which is not supported on iPhones.

 Since there is a part in the iPhone reader where AID registration occurs, I thought that if the flutter_nfc_hce plugin could provide the functionality to change the AID, it might prevent the automatic execution of Apple Pay. 

What are your thoughts on this matter?  Thank you.

**Comment by BugsOverBugs** [comment]
Yes, I am happy with the current behavior of iPhone and Apple Pay. It's just Apple doing things ;)

I implemented some of the requested features myself, refactored the code a bit and updated some methods to make them easier to use. Just check out the fork on my profile. If you wish, I will open a pull request for it. 
(I'm not sure if the mime types are fully covered yet and if `stopNfcHce` works as intended).

**Comment by deokgyuhan** [comment]
Thank you, Tom. Since I'm not very proficient with GitHub and have never collaborated using pull requests before, I downloaded the code you shared first. I'll work on it based on the refactored codebase and make the updates. I'll also mention the contributor BugsOverBugs in the README for the changes I've made. I've reviewed the changes to startNfcHce and stopNfcHce, as well as the refactoring of the code into a functional style. Although I haven't tested it yet, it seems fine in the code. I'm really grateful. 

I just realized that the default form of the startNfcHce function is to request with MIME type, as seen in the code. I apologize for not understanding this earlier due to my limited English skills. I'm really sorry for the trouble I may have caused. 

So, I'll work on storing and retrieving messages in external storage so that they can be retrieved even when the device is restarted, as we discussed earlier. As for the AID change part, I'll leave it for later updates, as I initially planned. 

I'll create the feature to store and retrieve messages from external storage and get in touch again when it's time for the update. I sincerely apologize for any inconvenience in communication and thank you for your assistance. 

Stay strong, and I'll get coding soon. I'll contact you through GitHub within a few days. Fighting! 😊

**Comment by deokgyuhan** [comment]
Hello, Tom!

 I store messages in internal storage and initialize them by reading from a file when the app starts. 

During my testing, even when I didn't execute "stopNfcHce" and simply closed the app, the NFC HCE continued to work.

I was able to read values correctly from the reader, and when I restarted the app, it still worked correctly. 

Based on the source code you shared with me yesterday, I conducted tests and encountered no issues.

 I have also updated the package on pub.dev and credited BugsOverBugs (https://github.com/BugsOverBugs) as a contributor to the update.

 Please review it, and if there are any further improvements or tasks we can collaborate on, feel free to leave a comment.

 I have learned a lot, especially from the code refactoring. Thank you.

**Comment by atanasyordanov21** [comment]
Hello,

I've been reading the entire discussion here, and now I'm glad to see that this plugin has become yet better with the new features you've implemented. Congratulations to both of you!

Though I still have two proposals for further improvements related to the latest development:

1. I was thinking it would make sense to have an optional parameter in `startNfcHce()`, for example `bool persistMessage = true`. Its purpose would be to disable writing the message to a file in case someone doesn't need such functionality.
2. It might be also good to delete the file with the message when calling `stopNfcHce()`.

Both have the purpose of leaving a clean state when using the service only in foreground and after stopping it.

Best regards!

**Comment by BugsOverBugs** [comment]
Hi atanasyordanov21, great ideas!

I just went through the code and added your requests, refactored some parts a bit and formatted it for maximum pub points ;)

@deokgyuhan please take a look at my changes. I didn't test if my attempt to delete the file with onDestroy works. Maybe you can confirm that.

**Comment by deokgyuhan** [comment]
> Hi atanasyordanov21, great ideas!
> 
> I just went through the code and added your requests, refactored some parts a bit and formatted it for maximum pub points ;)
> 
> @deokgyuhan please take a look at my changes. I didn't test if my attempt to delete the file with onDestroy works. Maybe you can confirm that.

Thank you, Tom. I've downloaded the source code and will review it now. I'll make the code changes, perform tests, and update it on pub.dev today. I'll also leave comments. I've followed you as well. Thank you. 😊

**Comment by deokgyuhan** [comment]
> Hello,
> 
> I've been reading the entire discussion here, and now I'm glad to see that this plugin has become yet better with the new features you've implemented. Congratulations to both of you!
> 
> Though I still have two proposals for further improvements related to the latest development:
> 
> 1. I was thinking it would make sense to have an optional parameter in `startNfcHce()`, for example `bool persistMessage = true`. Its purpose would be to disable writing the message to a file in case someone doesn't need such functionality.
> 2. It might be also good to delete the file with the message when calling `stopNfcHce()`.
> 
> Both have the purpose of leaving a clean state when using the service only in foreground and after stopping it.
> 
> Best regards!

Hi atanasyordanov21. I tried to apply the suggestions you made this morning, and BugsOverBugs helped me. I'll apply them quickly and update on pub.dev. Thanks again for the great advice, and keep up the good work.
 Oh, and I've followed you. 😊

**Comment by deokgyuhan** [comment]
I would like to express my gratitude once again to atanasyordanov21 and BugsOverBugs (Tom). 

I'd like to inform you about the following updates as of September 17, 2023:

```
**2023.09.17 Update**
1. Added the `persistMessage` option to the `startHce` function (with a default value of true).
2. Implemented the deletion of the internal storage file when executing the `stopNfcHce` function.
3. NFC HCE continues to operate even if the `stopNfcHce` function is not executed, and the app is closed. 
   In this scenario, when you run `startNfcHce` after a device reboot, it reads the NDEF message from 
   the internal storage file and initializes the message.
```

I  conducted tests on actual devices with the following four scenarios:
1. After executing `startNfcHce`, if the `stopNfcHce` function is not executed and the app is closed, 
  I verified whether the NFC HCE tag can be read by a reader. The result was successful.

2. After executing `startNfcHce`, if the `stopNfcHce` function is not executed, and the device is rebooted, 
   I verified whether it reads the NDEF message from the file. The result was successful.

3. After executing `startNfcHce` and then executing `stopNfcHce`,  I verified whether the file is deleted, and 
    the default message "Hello World" is displayed. The result was successful.

4. Additionally, I tested if the plugin functions correctly in the foreground, background, and when the screen is locked. 
   The result was successful.

Once again, I appreciate your interest in the flutter_nfc_hce plugin and your valuable feedback. 
Please review the update details, and if you have any further suggestions or areas that need improvement, 
feel free to share them in the comments.

Keep up the great work!

**Comment by atanasyordanov21** [comment]
Hello!

I have some further observations when testing this plugin. Once started it actually never stops even after `stopNfcHce()`. The only difference is that after `startNfcHce()` it transmits my custom message, and after `stopNfcHce()` it continues the transmission, but with the default "Hello world" message. The only way to stop it is to uninstall the app. It this a normal behavior? Is it possible to effectively stop the transmission and be silent?

Best regards!

**Comment by deokgyuhan** [comment]
> Hello!
> 
> I have some further observations when testing this plugin. Once started it actually never stops even after `stopNfcHce()`. The only difference is that after `startNfcHce()` it transmits my custom message, and after `stopNfcHce()` it continues the transmission, but with the default "Hello world" message. The only way to stop it is to uninstall the app. It this a normal behavior? Is it possible to effectively stop the transmission and be silent?
> 
> Best regards!

Hello atanasyordanov21, I apologize for checking the message late and responding. Firstly, I will review the source code again and read the Android developer documentation to find the relevant section. There's also another option, so I will try that and test whether `stopNfcHce()` works correctly, and I'll leave a comment. Thank you. I'll look into it further and hope to find a solution. I'll get in touch with you soon.

**Comment by deokgyuhan** [comment]
Hello atanasyordanov21

I apologize for reaching out so late. I returned to work two weeks ago, which has left me with very little time for programming. Programming is not my original profession, and since I've returned to my job, I haven't had the time to dedicate to it, which is why I couldn't get back to you sooner. I'm really sorry about this.

For now, the part I'm most suspicious about is the following content I mentioned before. Could changing this return value possibly solve the issue? I'm sharing the details in the hope that you can provide some feedback.

* reference: https://developer.android.com/reference/android/app/Service

> For started services, there are two additional major modes of operation they can decide to run in, depending on the value they return from onStartCommand(): [START_STICKY](https://developer.android.com/reference/android/app/Service#START_STICKY) is used for services that are explicitly started and stopped as needed, while [START_NOT_STICKY](https://developer.android.com/reference/android/app/Service#START_NOT_STICKY) or [START_REDELIVER_INTENT](https://developer.android.com/reference/android/app/Service#START_REDELIVER_INTENT) are used for services that should only remain running while processing any commands sent to them.

**Comment by atanasyordanov21** [comment]
Hello @deokgyuhan ,

You don't need to apologize for anything :)

I've never been doing native android development, and I'm not familiar with all these stuff. It would be great if you could find some time to experiment. Wish you a lot of success.

Greetings!

**Comment by martin-braun** [comment]
@deokgyuhan https://developer.android.com/reference/android/app/Service#START_REDELIVER_INTENT

> Constant to return from [onStartCommand(Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)): if this service's process is killed while it is started (after returning from [onStartCommand(Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int))), then it will be scheduled for a restart and the last delivered Intent re-delivered to it again via [onStartCommand(Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)). **This Intent will remain scheduled for redelivery until the service calls [stopSelf(int)](https://developer.android.com/reference/android/app/Service#stopSelf(int)) with the start ID provided to [onStartCommand(Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int))** The service will not receive a [onStartCommand(android.content.Intent, int, int)](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)) call with a null Intent because it will only be restarted if it is not finished processing all Intents sent to it (and any such pending events will be delivered at the point of restart).

If we look at https://github.com/deokgyuhan/flutter_nfc_hce/blob/be58963aa4a2d548edf56212564cd7bd351cffb4/android/src/main/kotlin/com/novice/flutter_nfc_hce/FlutterNfcHcePlugin.kt#L109-L110 we can clearly see that a new intent is created which gets passed to `stopService()`, so this cannot work. You actually have to remember the ID of the intent to properly stop its intent. Or do I miss something here?

I also noticed the fork https://github.com/agmo-ios-team/flutter_nfc_hce which implemented a different `enableApduService()` method (https://github.com/agmo-ios-team/flutter_nfc_hce/blob/5147ccddba079d8bc5724de896b51557c003446e/android/src/main/kotlin/com/novice/flutter_nfc_hce/FlutterNfcHcePlugin.kt#L153) which seems to install the service in a way that prevents its host app to close. I'm not sure why the author has chosen this approach when there is also `startForeground()`. Maybe because a foreground service will be visible in the notification arena. Their implementation looks as it's try to cover the case where an app might be put into the background while the service was started only for a set duration and the app gets killed by the system before `stopNfcHce()` was called.

But in this case, it's a simple use case that just needs `onStartCommand()` to return `START_NON_STICKY` I believe. For background HCE that should run past the app's lifecycle, iOS suggests the presentment intent assertion. `[START_REDELIVER_INTENT](https://developer.android.com/reference/android/app/Service#START_REDELIVER_INTENT)` seems appropriate on the Android end, if the service was properly stopped as mentioned above.

So what do I see necessary here:

- #7 should be made reality, but it requires the HCE Entitlement
- Android should remember the intent ID in the shared prefs and provide it
- `persistentMessage` might be refactored to `keepAlive`, and if its true:
  - [Android] It should return START_REDELIVER_INTENT, otherwise it should return START_NON_STICKY
  - [Android] It should store the message itself in the shared prefs, so no FileSystem permissions are necessary (this all should be skipped if `keepAlive` is false)
  - [Android] Maybe prevent the app from dying (this is what @agmo-ios-team did, but it would not help if there was an issue with `START_REDELIVER_INTENT` when rebooting the device)
  - [Android] Maybe consider `startForeground()`
  - [iOS] It should leverage the Presentment Intent Assertion
- #3 looks also nice and should be merged

(For Android we could also provide an Enum that select any of the persistence methods..)
